/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sandbox;

public class MyFirstProgram {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MyFirstProgram().getGreeting());
    }
}
